/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoImportTest: typeof import('./src/components/AutoImportTest.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    BannerAds: typeof import('./src/components/BannerAds.vue')['default']
    BatchCreateSKUs: typeof import('./src/components/BatchCreateSKUs.vue')['default']
    Button: typeof import('primevue/button')['default']
    CarouselAds: typeof import('./src/components/CarouselAds.vue')['default']
    CategoryNav: typeof import('./src/components/CategoryNav.vue')['default']
    CategoryNavigation: typeof import('./src/components/CategoryNavigation.vue')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Drawer: typeof import('primevue/drawer')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    FormField: typeof import('@primevue/forms/formfield')['default']
    GoogleLoginButton: typeof import('./src/components/GoogleLoginButton.vue')['default']
    ImageSelector: typeof import('./src/components/ImageSelector.vue')['default']
    ImageUpload: typeof import('./src/components/ImageUpload.vue')['default']
    InputGroup: typeof import("primevue/inputgroup")["default"]
    InputGroupAddon: typeof import("primevue/inputgroupaddon")["default"]
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Paginator: typeof import('primevue/paginator')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    PrimeCrudTemplate: typeof import('./src/components/template2/PrimeCrudTemplate.vue')['default']
    PrimeMenu: typeof import('./src/components/template2/PrimeMenu.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    ProductSearch: typeof import('./src/components/ProductSearch.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SimplifiedImageSelector: typeof import('./src/components/SimplifiedImageSelector.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    Tooltip: typeof import('./src/components/Tooltip.vue')['default']
    TreeSelect: typeof import("primevue/treeselect")["default"]
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
